# Docker compose file used to load the broker, ASR, and dialogue_manager
# TTS still to do
version: "3"

networks:
  asrmqtt:
    driver: bridge

services:
  broker:
    image: 'eclipse-mosquitto:2.0.15'
    networks:
      - asrmqtt
    restart: always
    container_name: 'mqtt-broker'
    hostname: 'mqtt-broker'
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  asr:
    image: 'alphacep/kaldi-${LANG}:latest'
    container_name: 'kaldi_asr'
    hostname: "asr"
    networks:
      - asrmqtt
    ports:
      - '2700:2700'

  nlu:
    image: 'rasa/rasa:3.5.14-full'
    volumes:
      - ../rasa/:/app
    command: run --enable-api --port 5005
    hostname: "rasa"
    networks:
      - asrmqtt
    ports:
      - '5005:5005'
