# language is added to topic to which the results are sent
#/voskasr/asrresult/<lang>
language: en

# websocket uri of kaldi/vosk server
uri: "ws://0.0.0.0:2700/"
# adaptation_state_infile="state"
# adaptation_state_outfile="state"

# Address of MQTT broker
# docker compose: mqtt_address: mqtt-broker
mqtt_address: localhost

# Audio parameter

# Sennheiser PC 8
#channels: 1     # is default
#use_channel: 0  # is default
sample_rate: 44100
device: Sennheiser

# To use ReSpeaker V2, comment the previous and uncomment the `device` line
# check if the hardware device in gstmicpipeline.py is correct
# device: ReSpeaker
# channels: 6
# use_channel: 0 # combo channel
# sample_rate: 16000

asr_sample_rate: 8000
