# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 5
- name: DIETClassifier
  epochs: 30
  constrain_similarities: true
# - name: RegexEntityExtractor
#       # text will be processed with case insensitive as default
#   case_sensitive: false
#       # use lookup tables to extract entities
#   use_lookup_tables: true
#       # use regexes to extract entities
#   use_regexes: True
#       # use match word boundaries for lookup table
#       #"use_word_boundaries": True
- name: EntitySynonymMapper
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1
assistant_id: 20230908-092757-tangy-crescendo
